config/routes.rb
Rails.application.routes.draw do

  # Routes to ActiveAdmin
  get '/admin/companies', to: redirect('/admin/companies/1')
  get '/admin/contatos', to: redirect('/admin/contatos/1')
  post '/load_video' => 'jobs#load_vimeo_video'
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  # Jobs / Messages
  scope "(:locale)", locale: /en|es|pt/ do
    resources :messages, only: [:new, :create]
    resources :jobs, only: [:show]
    get '/locked/:id' => 'jobs#locked'
  end
  
  # Root
  get '/:locale' => 'pages#home'
  root to: "pages#home"
 
end

app/models/message.rb
class Message
	include ActiveModel::Model
	include ActiveModel::Conversion
	include ActiveModel::Validations
	attr_accessor :name, :email, :subject, :content, :department, :file

	validates :name, presence: true
	validates :email, presence: true, format: { with: /\S+@\S+\.\S+/ix }
	validates :subject, presence: true
	validates :content, presence: true
	validates :department, presence: true
	validate :file_size_validation

private
	def file_size_validation
		if file.present?
    		errors[:file] << "Should be less than 5MB" if file.size > 5.megabytes
    	end
  	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  	def new
  		@message = Message.new
 	end

	def create
	    @message = Message.new(message_params)
	    
	    # puts @message.valid?
	    # if @message.valid?
	    # if true
	    if verify_recaptcha(model: @message, attribute: :recaptcha) and @message.valid?

	    	# Get the correct e-mail
	    	mail_to = Department.find(@message.department).email

	    	# Deliver the email
	      	MessageMailer.message_me(@message, mail_to).deliver_now

      		respond_to do |format|
			    format.html { redirect_to root_path }
			    format.js {
			    	@message = Message.new
			    	flash.now[:success] = true
			    	render :new
			    }
		    end
	    else
	    	puts @message.errors.full_messages
	      	respond_to do |format|
		    	format.js { render :new }
		        format.json { render json: @message.errors, status: :unprocessable_entity }
		    end
	    end
  	end

  	private
	  	def message_params
	    	params.require(:message).permit(:name, :email, :subject, :content, :department, :file)
	  	end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_new.html.erb
<%= form_for @message, url: messages_path(locale: I18n.locale), remote: true, html: {lang: I18n.locale} do |f| %>
  
  <div id="error_explanation">

    <div class="field">
      <%= f.text_field :name, placeholder: t('home.contact.name'), required: true, lang: I18n.locale %>
    </div>

    <div class="field">
      <%= f.email_field :email, placeholder: t('home.contact.email'), required: true %>
    </div>

    <div class="field">
      <% if Department.count > 1 %>
        <%= f.select(:department, options_for_select(Department.all.collect{ |d| [d.name, d.id] }), {prompt: t('home.contact.department')}, required: true) 
        %>
      <% else %>
        <%= f.select(:department, options_for_select(Department.all.collect{ |d| [d.name, d.id] }), required: true)
        %>
      <% end %>
    </div>

    <div class="field">
      <%= f.text_field :subject, placeholder: t('home.contact.subject'), required: true %>
    </div>

    <div class="field">
      <%= f.text_area :content, placeholder: t('home.contact.content'), required:true, rows: 8 %>
    </div>

    <div class="field">
      <% if @message.errors[:file].any? %>
        <p class="file-size-error"><%= t('home.contact.file_size_error')%></p>
        <div class="field_with_errors">
      <% end %>
      <label class="custom-file-upload" data-label="<%= t('home.contact.attach') %>">
          <input id="message_file" type="file" name="message[file]"/>
          <span><%= t('home.contact.attach') %></span>
      </label>
      <% if @message.errors[:file].any? %>
        </div>
      <% end %>
    </div>

    <div class="field" id="my-awesome-captcha">
      <% if @message.errors[:recaptcha].any? %>
        <p class="recaptcha-error"><%= @message.errors[:recaptcha].first %></p>
      <% end %>
    	<%= recaptcha_tags(theme: "dark") %>
    </div>

    <div class="actions">
      <%= f.submit t('home.contact.submit'), class: 'submit center-block text-center' %>
    </div>
  </div>
<% end %>

app/views/messages/new.js.erb
// If succeeded, render new form and prepend success message. Otherwise, show errors.
<% if flash[:success] == true %>
	$('#new_message').parent().html("<%= j render('/messages/new')%>");
	$('#new_message').prepend("<p class='success'><%= t('home.contact.success') %></p>");
<% else %>
	$('#new_message').parent().html("<%= j render('/messages/new')%>");
<% end %>

// Binding events to inputs
formValidations();