config/routes.rb
Rails.application.routes.draw do

  # Routes to ActiveAdmin
  get '/admin/companies', to: redirect('/admin/companies/1')
  get '/admin/contatos', to: redirect('/admin/contatos/1')
  post '/load_video' => 'jobs#load_vimeo_video'
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  # Jobs / Messages
  scope "(:locale)", locale: /en|es|pt/ do
    resources :messages, only: [:new, :create]
    resources :jobs, only: [:show]
    get '/locked/:id' => 'jobs#locked'
  end
  
  # Root
  get '/:locale' => 'pages#home'
  root to: "pages#home"
 
end

app/models/job.rb
class Job < ActiveRecord::Base

	belongs_to :category

	validates :video_url, presence: true
	validates :video_id, presence: true
	validates :video_thumb_small, presence: true
	validates :video_thumb_medium, presence: true
	validates :video_thumb_large, presence: true
	validate :id_uniqueness_validation, on: [:create]

	# Validating Vimeo video or album
	validates :video_url, format: { with: /https?:\/\/(?:www\.|player\.)?vimeo.com\/(?:channels\/(?:\w+\/)?|groups\/([^\/]*)\/videos\/|album\/(\d+)\/video\/|video\/|)(\d+)(?:$|\/|\?)/ix }
	
	#
	# 	Title
	#
	# Try to always shows a title. 
	def title?()
		return (title() != nil)
	end

	def title()
		if I18n.locale == :en
			if title_en.present?
				return title_en
			elsif title_pt.present?
				return title_pt
			elsif title_es.present?
				return title_es
			end
		elsif I18n.locale == :pt
			if title_pt.present?
				return title_pt
			elsif title_en.present?
				return title_en
			elsif title_es.present?
				return title_es
			end
		elsif I18n.locale == :es
			if title_es.present?
				return title_es
			elsif title_en.present?
				return title_en
			elsif title_pt.present?
				return title_pt
			end
		end
	end

	#
	# 	Synopsis
	#
	def synopsis?()
		return (synopsis() != nil)
	end

	def synopsis()
		if I18n.locale == :en and synopsis_en.present?
			return synopsis_en
		elsif I18n.locale == :pt and synopsis_pt.present?
			return synopsis_pt
		elsif I18n.locale == :es and synopsis_es.present?
			return synopsis_es
		end
	end

	#
	# 	Format
	#
	def format?()
		return (format() != nil)
	end

	def format()
		if I18n.locale == :en and format_en.present?
			return format_en
		elsif I18n.locale == :pt and format_pt.present?
			return format_pt
		elsif I18n.locale == :es and format_es.present?
			return format_es
		end
	end

	#
	# 	Genre
	#
	def genre?()
		return (genre() != nil)
	end

	def genre()
		if I18n.locale == :en and genre_en.present?
			return genre_en
		elsif I18n.locale == :pt and genre_pt.present?
			return genre_pt
		elsif I18n.locale == :es and genre_es.present?
			return genre_es
		end
	end

	#
	# 	Subgenre
	#
	def subgenre?()
		return (subgenre() != nil)
	end

	def subgenre()
		if I18n.locale == :en and subgenre_en.present?
			return subgenre_en
		elsif I18n.locale == :pt and subgenre_pt.present?
			return subgenre_pt
		elsif I18n.locale == :es and subgenre_es.present?
			return subgenre_es
		end
	end

	#
	# 	Running Time
	#
	def running_time?()
		return (running_time() != nil)
	end

	def running_time()
		if I18n.locale == :en and running_time_en.present?
			return running_time_en
		elsif I18n.locale == :pt and running_time_pt.present?
			return running_time_pt
		elsif I18n.locale == :es and running_time_es.present?
			return running_time_es
		end
	end

	#
	# 	Target
	#
	def target?()
		return (target() != nil)
	end

	def target()
		if I18n.locale == :en and target_en.present?
			return target_en
		elsif I18n.locale == :pt and target_pt.present?
			return target_pt
		elsif I18n.locale == :es and target_es.present?
			return target_es
		end
	end

	#
	# 	Created By
	#
	def created_by?()
		return (created_by() != nil)
	end

	def created_by()
		if I18n.locale == :en and created_by_en.present?
			return created_by_en
		elsif I18n.locale == :pt and created_by_pt.present?
			return created_by_pt
		elsif I18n.locale == :es and created_by_es.present?
			return created_by_es
		end
	end

	#
	# 	Written By
	#
	def written_by?()
		return (written_by() != nil)
	end

	def written_by()
		if I18n.locale == :en and written_by_en.present?
			return written_by_en
		elsif I18n.locale == :pt and written_by_pt.present?
			return written_by_pt
		elsif I18n.locale == :es and written_by_es.present?
			return written_by_es
		end
	end

	#
	# 	Directed By
	#
	def directed_by?()
		return (directed_by() != nil)
	end

	def directed_by()
		if I18n.locale == :en and directed_by_en.present?
			return directed_by_en
		elsif I18n.locale == :pt and directed_by_pt.present?
			return directed_by_pt
		elsif I18n.locale == :es and directed_by_es.present?
			return directed_by_es
		end
	end

	#
	# 	Status
	#
	def status?()
		return (status() != nil)
	end

	def status()
		if I18n.locale == :en and status_en.present?
			return status_en
		elsif I18n.locale == :pt and status_pt.present?
			return status_pt
		elsif I18n.locale == :es and status_es.present?
			return status_es
		end
	end

	private
		def id_uniqueness_validation()
			if Job.where(video_id: self.video_id).any?
				errors.add(:video_url, "Este vídeo já foi adicionado!")
			end
		end

end

# Fields / Columns:
#   t.string :title_pt
#   t.string :title_en 
#   t.string :title_es 
#   t.string :password  (if blank, it's public)
#   t.text :synopsis_pt
#   t.text :format_pt
#   t.text :genre_pt
#   t.text :subgenre_pt
#   t.text :running_time_pt 
#   t.text :target_pt
#   t.text :created_by_pt 
#   t.text :written_by_pt
#   t.text :directed_by_pt
# 	t.text :synopsis_es
#   t.text :synopsis_en
#   t.text :format_es
#   t.text :format_en
#   t.text :genre_es
#   t.text :genre_en
#   t.text :subgenre_es
#   t.text :subgenre_en
#   t.text :running_time_es
#   t.text :running_time_en
#   t.text :target_es
#   t.text :target_en
#   t.text :created_by_es
#   t.text :created_by_en
#   t.text :written_by_es
#   t.text :written_by_en
#   t.text :directed_by_es
#   t.text :directed_by_en
#   t.text :status 
#   t.text :player 

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	include OwnVimeo

	def show()
		job = Job.find(params[:id])

		# Public job (no password) or correct password
		if (job.password.blank? or (params[:password] and job.password == params[:password]))
			@job = job

			if job.password.present?
				flash.now[:correct_password] = true
			end

			respond_to do |format|
			    format.html { redirect_to root_path }
			    format.js { render 'show' }
		    end

		# Wrong password
		elsif (job.password.present? and params[:password] and (job.password != params[:password]))
			respond_to do |format|
			    format.html { redirect_to root_path }
			    format.js { flash.now[:wrong_password] = true }
		    end
		else
			redirect_to controller: "jobs", action: "locked", id: params[:id], locale: I18n.locale
		end

	end

	def locked()
		job = Job.find(params[:id])
		@id = job.id
		@year = job.year
		@title = job.title()

		respond_to do |format|
		    format.html { redirect_to root_path }
		    format.js { render 'locked' }
	    end
	end

	def load_vimeo_video()

		info = get_vimeo_video(params[:vimeo_id])

		if (info)
			render json: {
				"id": params[:vimeo_id],
				"title": info[:title],
				"description": info[:description],
				"thumbnail_small": info[:thumbnail_small],
				"thumbnail_medium": info[:thumbnail_medium],
				"thumbnail_large": info[:thumbnail_large],
				"duration": info[:duration],
				"year": info[:year]
			}
		else
			render json: {}, status: 400
		end

	end
end

app/views/jobs/_locked.html.erb
<div class="vertical-alignment-helper">
  	<div class="modal-dialog modal-lg vertical-align-center" role="document">
	    <div class="modal-content">
	      <div class="modal-body locked-body">

	      	<!-- Extra Small / Small devices -->
	      	<div class="row hidden-md hidden-lg">

	      		<!-- Meta information -->
	      		<div class="col-xs-12 col-video-description">
	          	<div class="row meta">
	          		<div class="col-xs-10">
	          			<p class="video-title">
		          			<%= @title %>
	          			</p>
	          			
	          			<p class="video-year">
	          				<% if @year.present? %>
		          				(<%= @year %>)
		          			<% end %>
          				</p>
	          		</div>
	          		<div class="col-xs-2" style="display: block">
	          			<%= image_tag("fechar_popup.svg", alt: t('home.close_popup'), title: t('home.close_popup'), height: 32, width: 32, class: "close", data: {dismiss: "modal", label: "Close"}) %>
	          		</div>
	          	</div>
	          </div>

	          <div class="col-xs-12 col-video">
            	<div class="locked-video">
            		<%= image_tag("cadeado.svg", class: "locked-image", alt: t('home.job.locked.line_one') + t('home.job.locked.line_two'), title: t('home.job.locked.line_one') + t('home.job.locked.line_two')) %>
            		<p><%= t('home.job.locked.line_one') %></p>
            		<p><%= t('home.job.locked.line_two') %></p>
            	</div>
	          </div>

	          <div class="col-xs-12 col-video-description">
					<!-- Locked content -->
		          	<div class="row locked">
		          		<div class="col-xs-12">
		          			<p class="description-title">
		          				<%= t('home.job.locked.title') %>
		          			</p>
		          			<p class="description-text">
		          				<%= t('home.job.locked.description') %>
		          			</p>
		          			<%= form_tag(job_path(id: @id), method: :get, remote: true) do %>
		          			  <%= hidden_field_tag 'id', @id %>
							  <%= password_field_tag(:password, nil, class: "unlock_password_text", placeholder: t('home.job.locked.password_placeholder')) %>
						  	  <%= submit_tag(t('home.job.locked.button'), class: "unlock_password_button") %>
							<% end %>
		          		</div>
		          	</div>
	          </div>
	        </div>

	      	<!-- Medium / Large devices -->
	        <div class="row hidden-xs hidden-sm hidden-ms">
	          <div class="col-md-8 col-video">
            	<div class="locked-video">
            		<%= image_tag("cadeado.svg", class: "locked-image", alt: t('home.job.locked.line_one') + t('home.job.locked.line_two'), title: t('home.job.locked.line_one') + t('home.job.locked.line_two')) %>
            		<p><%= t('home.job.locked.line_one') %></p>
            		<p><%= t('home.job.locked.line_two') %></p>
            	</div>
	          </div>
	          <div class="col-md-4 col-video-description">

	          	<!-- Meta information -->
	          	<div class="row meta">
	          		<div class="col-md-10">
	          			<p class="video-title">
	          				<%= @title %>
	          			</p>
	          			<p class="video-year">
	          				<% if @year.present? %>
		          				(<%= @year %>)
		          			<% end %>
          				</p>
	          		</div>
	          		<div class="col-md-2">
	          			<%= image_tag("fechar_popup.svg", alt: t('home.close_popup'), title: t('home.close_popup'), height: 32, width: 32, class: "close", data: {dismiss: "modal", label: "Close"}) %>
	          		</div>
	          	</div>

				<!-- Locked content -->
	          	<div class="row locked">
	          		<div class="col-md-12">
	          			<p class="description-title">
	          				<%= t('home.job.locked.title') %>
	          			</p>
	          			<p class="description-text">
	          				<%= t('home.job.locked.description') %>
	          			</p>
	          			<%= form_tag(job_path(id: @id), method: :get, remote: true) do %>
	          			  <%= hidden_field_tag 'id', @id %>
						  <%= password_field_tag(:password, nil, class: "unlock_password_text", placeholder: t('home.job.locked.password_placeholder')) %>
						  <%= submit_tag(t('home.job.locked.button'), class: "unlock_password_button") %>
						<% end %>
	          		</div>
	          	</div>
	          </div>
	        </div>
	      </div>
	    </div><!-- /.modal-content -->
  	</div><!-- /.modal-dialog -->
</div><!-- /.vertical alignment-helper -->

app/views/jobs/_modal.html.erb
<div class="vertical-alignment-helper">
  	<div class="modal-dialog modal-lg vertical-align-center" role="document">
	    <div class="modal-content">
	      <div class="modal-body">

	      	<!-- Extra Small / Small devices -->
	      	<div class="row hidden-md hidden-lg">

	      		<!-- Meta information -->
	      		<div class="col-xs-12 col-video-description">
	          	<div class="row meta">
	          		<div class="col-xs-10">
	          			<p class="video-title">
		          			<%= @job.title %>
	          			</p>
	          			<p class="video-year">
          					<% if @job.year.present? %>
	          					(<%= @job.year %>)
		          			<% end %>
      					</p>
	          		</div>
	          		<div class="col-xs-2" style="display: block">
	          			<%= image_tag("fechar_popup.svg", alt: t('home.close_popup'), title: t('home.close_popup'), height: 32, width: 32, class: "close", data: {dismiss: "modal", label: "Close"}) %>
	          		</div>
	          	</div>
	          </div>

	          <div class="col-xs-12 col-video">
	          	<div class="embed-responsive embed-responsive-16by9">
        		<iframe class="video embed-responsive-item" src="//player.vimeo.com/video/<%= @job.video_id %>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
            	</div>
	          </div>

	          <div class="col-xs-12 col-video-description">
		          	<div class="row">
		          		
			          	<!-- Synopsis -->
			          	<% if @job.synopsis? %>
			          		<div class="col-xs-12 col-sm-6 synopsis">
			          			<p class="description-title">
			          				<%= t('home.job.synopsis') %>
			          			</p>
			          			<p class="description-text">
			          				<%= @job.synopsis %>
			          			</p>
			          		</div>
			          	<% end %>

			          	<!-- Infos / Datasheet -->
		          		<div class="col-xs-12 col-sm-6 datasheet">
		          		<p class="description-title"><%= t('home.job.info') %></p>
		          		<table class="table table-striped description-text table-hover"><tbody>

          					<!-- Title -->
          					<tr>
          						<td><%= t('home.job.title') %></td>
          						<td>
          							<%= simple_format(@job.title, {}, wrapper_tag: "span")%>
          						</td>
          					</tr>

          					<!-- Format -->
          					<% if @job.format?() %>
	          					<tr> 
	          						<td><%= t('home.job.format') %></td>
	          						<td>
	          							<%= simple_format(@job.format(), {}, wrapper_tag: "span") %>
	          						</td>
	          					</tr>
		          			<% end %>

		          			<!-- Genre -->
		          			<% if @job.genre?() %>
	          					<tr> 
	          						<td><%= t('home.job.genre') %></td>
	          						<td>
	          							<%= simple_format(@job.genre(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Subgenre -->
	          				<% if @job.subgenre?() %>
	          					<tr> 
	          						<td><%= t('home.job.subgenre') %></td>
	          						<td>
	          							<%= simple_format(@job.subgenre(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Running Time -->
	          				<% if @job.running_time?() %>
	          					<tr> 
	          						<td><%= t('home.job.running_time') %></td>
	          						<td>
	          							<%= simple_format(@job.running_time(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Target -->
	          				<% if @job.target?() %>
	          					<tr> 
	          						<td><%= t('home.job.target') %></td>
	          						<td>
	          							<%= simple_format(@job.target(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Created By -->
	          				<% if @job.created_by?() %>
	          					<tr> 
	          						<td class="text-nowrap"><%= t('home.job.created_by') %></td>
	          						<td>
	          							<%= simple_format(@job.created_by(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Written By -->
	          				<% if @job.written_by?() %>
	          					<tr> 
	          						<td><%= t('home.job.written_by') %></td>
	          						<td>
	          							<%= simple_format(@job.written_by(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>
	          				
	          				<!-- Directed By -->
	          				<% if @job.directed_by?() %>
	          					<tr> 
	          						<td><%= t('home.job.directed_by') %></td>
	          						<td>
	          							<%= simple_format(@job.directed_by(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Status -->
	          				<% if @job.status?() %>
	          					<tr> 
	          						<td><%= t('home.job.status') %></td>
	          						<td>
	          							<%= simple_format(@job.status(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Player -->
	          				<% if @job.player.present? %>
	          					<tr> 
	          						<td><%= t('home.job.player') %></td>
	          						<td><%= simple_format(@job.player, {}, wrapper_tag: "span") %></td>
	          					</tr>
	          				<% end %>

		          		</tbody></table>
						</div>
					</div>
	          </div>
	        </div>




	      	<!-- Medium / Large devices -->
	        <div class="row hidden-xs hidden-sm hidden-ms">
	          <div class="col-md-8 col-video">
	          	<div class="embed-responsive embed-responsive-16by9">
        		<iframe class="video embed-responsive-item" src="//player.vimeo.com/video/<%= @job.video_id %>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
            	</div>
	          </div>
	          <div class="col-md-4 col-video-description">

	          	<!-- Meta information -->
	          	<div class="row meta">
	          		<div class="col-md-10">
	          			<p class="video-title">
	          				<%= @job.title %>
	          			</p>
	          			
          				<p class="video-year">
          					<% if @job.year.present? %>
	          					(<%= @job.year %>)
		          			<% end %>
      					</p>
	          		</div>
	          		<div class="col-md-2">
	          			<%= image_tag("fechar_popup.svg", alt: t('home.close_popup'), title: t('home.close_popup'), height: 32, width: 32, class: "close", data: {dismiss: "modal", label: "Close"}) %>
	          		</div>
	          	</div>

	          	<!-- Synopsis -->
	          	<% if @job.synopsis %>
		          	<div class="row synopsis">
		          		<div class="col-md-12">
		          			<p class="description-title">
		          				<%= t('home.job.synopsis') %>
		          			</p>
		          			<p class="description-text">
		          				<%= @job.synopsis %>
		          			</p>
		          		</div>
		          	</div>
	          	<% end %>

	          	<!-- Infos / Datasheet -->
	          	<div class="row datasheet">
	          		<div class="col-md-12">
	          		<p class="description-title"><%= t('home.job.info') %></p>
	          		<table class="table table-striped description-text table-hover"><tbody>

	          			<!-- Title -->
          					<tr>
          						<td><%= t('home.job.title') %></td>
          						<td>
          							<%= simple_format(@job.title, {}, wrapper_tag: "span")%>
          						</td>
          					</tr>

          					<!-- Format -->
          					<% if @job.format?() %>
	          					<tr> 
	          						<td><%= t('home.job.format') %></td>
	          						<td>
	          							<%= simple_format(@job.format(), {}, wrapper_tag: "span") %>
	          						</td>
	          					</tr>
		          			<% end %>

		          			<!-- Genre -->
		          			<% if @job.genre?() %>
	          					<tr> 
	          						<td><%= t('home.job.genre') %></td>
	          						<td>
	          							<%= simple_format(@job.genre(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Subgenre -->
	          				<% if @job.subgenre?() %>
	          					<tr> 
	          						<td><%= t('home.job.subgenre') %></td>
	          						<td>
	          							<%= simple_format(@job.subgenre(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Running Time -->
	          				<% if @job.running_time?() %>
	          					<tr> 
	          						<td><%= t('home.job.running_time') %></td>
	          						<td>
	          							<%= simple_format(@job.running_time(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Target -->
	          				<% if @job.target?() %>
	          					<tr> 
	          						<td><%= t('home.job.target') %></td>
	          						<td>
	          							<%= simple_format(@job.target(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Created By -->
	          				<% if @job.created_by?() %>
	          					<tr> 
	          						<td class="text-nowrap"><%= t('home.job.created_by') %></td>
	          						<td>
	          							<%= simple_format(@job.created_by(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Written By -->
	          				<% if @job.written_by?() %>
	          					<tr> 
	          						<td><%= t('home.job.written_by') %></td>
	          						<td>
	          							<%= simple_format(@job.written_by(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>
	          				
	          				<!-- Directed By -->
	          				<% if @job.directed_by?() %>
	          					<tr> 
	          						<td><%= t('home.job.directed_by') %></td>
	          						<td>
	          							<%= simple_format(@job.directed_by(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Status -->
	          				<% if @job.status?() %>
	          					<tr> 
	          						<td><%= t('home.job.status') %></td>
	          						<td>
	          							<%= simple_format(@job.status(), {}, wrapper_tag: "span") %>
          							</td>
	          					</tr>
	          				<% end %>

	          				<!-- Player -->
	          				<% if @job.player.present? %>
	          					<tr> 
	          						<td><%= t('home.job.player') %></td>
	          						<td><%= simple_format(@job.player, {}, wrapper_tag: "span") %></td>
	          					</tr>
	          				<% end %>

	          		</tbody></table>
	          		</div>
				</div>
	          </div>
	        </div>
	      </div>
	    </div><!-- /.modal-content -->
  	</div><!-- /.modal-dialog -->
</div><!-- /.vertical alignment-helper -->

app/views/jobs/locked.js.erb
$('#myModal').html("<%= j render('/jobs/locked')%>");

app/views/jobs/show.js.erb
<% if flash.now[:wrong_password] == true %>
	$('.unlock_password_text').addClass('unlock_password_text_wrong');
<% else %>
	$('#myModal').html("<%= j render('/jobs/modal')%>")
<% end %>

<% if flash.now[:correct_password] == true %>
	myOwnDelay(function(){
		setModalHeight();
    }, 350);
<% end %>